name: 

on:
  workflow_dispatch:
  
  pull_request:
    branches:
      - main

    paths:
        - starter/backend/**

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install pipenv
        run: pip install pipenv && pip install flake8

      - name: Run linter
        run: cd starter/backend && pipenv run lint

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install pipenv
        run: pip install pipenv && pip install flake8

      - name: Install dependencies
        run: cd starter/backend && pipenv install

      - name: Run test
        run: cd starter/backend && pipenv run test

  build_deploy:
      runs-on: ubuntu-latest
      needs: [lint, test]

      steps:
        # Simulate a Deployment
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v2
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            #aws-session-token: ${{secrets.AWS_SESSION_TOKEN}}
            aws-region: us-east-1

        - name: Login to Amazon 
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v2

        - name: Checkout code
          uses: actions/checkout@v3

        - name: Build and push to ECR
          uses: docker/build-push-action@v4
          with:
            context: starter/backend
            push: true
            tags: 961247951538.dkr.ecr.us-east-1.amazonaws.com/backend:latest
            build-args: |
              REACT_APP_MOVIE_API_URL=${{ env.REACT_APP_MOVIE_API_URL }}
        
        - name: Set up kubectl
          uses: azure/setup-kubectl@v3
          with:
            version: 'latest'

        - name: Deploy to Kubernetes
          working-directory: starter/backend/k8s
          run: |
            aws eks update-kubeconfig --name cluster --region us-east-1
            kustomize edit set image backend=961247951538.dkr.ecr.us-east-1.amazonaws.com/backend:latest
            kustomize build | kubectl apply -f -