name: 

env: 
  REACT_APP_MOVIE_API_URL: http://localhost:5000

on:
  workflow_dispatch:
  
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: cd starter/frontend && npm ci

      - name: Run linter
        run: cd starter/frontend && npm run lint

  test:
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: cd starter/frontend && npm ci

      - name: Run linter
        run: cd starter/frontend && CI=true npm test


  build:
    runs-on: ubuntu-latest
    needs: [lint, test]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name:
        run: |
          docker build --build-arg=${{ env.REACT_APP_MOVIE_API_URL' }} --tag=mp-frontend:latest . \
          docker run --name mp-frontend -p 3000:3000 -d mp-frontend]



